/**
 * https://www.bluetooth.com/specifications/assigned-numbers/generic-access-profile/
 */
export enum GapAttributeCode {
	FLAGS = 0x01,
	INCOMPLETE_LIST_OF_SERVICE_UUIDS_16_BIT = 0x02,
	COMPLETE_LIST_OF_SERVICE_UUIDS_16_BIT = 0x03,
	INCOMPLETE_LIST_OF_SERVICE_UUIDS_32_BIT = 0x04,
	COMPLETE_LIST_OF_SERVICE_UUIDS_32_BIT = 0x05,
	INCOMPLETE_LIST_OF_SERVICE_UUIDS_128_BIT = 0x06,
	COMPLETE_LIST_OF_SERVICE_UUIDS_128_BIT = 0x07,
	LOCAL_NAME_SHORTENED = 0x08,
	LOCAL_NAME_COMPLETE = 0x09,
	TX_POWER_LEVEL = 0x0A,
	DEVICE_CLASS = 0x0D,
	SIMPLE_PAIRING_HASH_C_192 = 0x0E, // ALIAS - Simple Pairing Hash C
	SIMPLE_PAIRING_RANDOMIZER_R_192 = 0x0F, // ALIAS - Simple Pairing Randomizer R
	DEVICE_ID = 0x10, // ALIAS - Security Manager TK Value
	SECURITY_MANAGER_OUT_OF_BAND_FLAGS = 0x11,
	SLAVE_CONNECTION_INTERVAL_RANGE = 0x12,
	LIST_OF_SERVICE_SOLICITATION_UUIDS_16_BIT = 0x14,
	LIST_OF_SERVICE_SOLICITATION_UUIDS_128_BIT = 0x15,
	SERVICE_DATA_UUID_16_BIT = 0x16, // ALIAS - Service Data,
	TARGET_ADDRESS_PUBLIC = 0x17,
	TARGET_ADDRESS_RANDOM = 0x18,
	APPEARANCE = 0x19,
	ADVERTISING_INTERVAL = 0x1A,
	LE_BLUETOOTH_DEVICE_ADDRESS = 0x1B,
	LE_ROLE = 0x1C,
	SIMPLE_PAIRING_HASH_C_256 = 0x1D,
	SIMPLE_PAIRING_RANDOMIZER_R_256 = 0x1E,
	LIST_OF_SERVICE_SOLICITATION_UUIDS_32_BIT = 0x1F,
	SERVICE_DATA_UUID_32_BIT = 0x20,
	SERVICE_DATA_UUID_128_BIT = 0x21,
	LE_SECURE_CONNECTIONS_CONFIRMATION_VALUE = 0x22,
	LE_SECURE_CONNECTIONS_RANDOM_VALUE = 0x23,
	URI = 0x24,
	INDOOR_POSITIONING = 0x25,
	TRANSPORT_DISCOVERY_DATA = 0x26,
	LE_SUPPORTED_FEATURES = 0x27,
	CHANNEL_MAP_UPDATE_INDICATION = 0x28,
	PB_ADV = 0x29,
	MESH_MESSAGE = 0x2A,
	MESH_BEACON = 0x2B,
	BIG_INFO = 0x2C,
	BROADCAST_CODE = 0x2D,
	INFORMATION_DATA_3D = 0x3D,
	MANUFACTURER_SPECIFIC_DATA = 0xFF
}
